sudo: required
language: node_js
node_js:
  - "4.1"
  - "5.3"
  - "6.0"
branches:
  only:
    - master
env:
  global:
    - CXX=g++-4.8
  matrix:
    - GIT_VERSION=default
    - GIT_VERSION=edge
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm install -g grunt-cli
  - if [ "$GIT_VERSION" = "edge" ]; then sudo add-apt-repository ppa:git-core/ppa -y && sudo apt-get update -q && sudo apt-get install -y git; fi
  - git config --global user.email "test@testy.com"
  - git config --global user.name "Test testy"
  - git version
  - grunt -d
after_script:
  - grunt travisnpmpublish
